# Generated by Django 5.2.8 on 2025-11-19 18:53

import django.db.models.deletion
import documents.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.utils.get_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_address', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('items_data', models.JSONField(blank=True, default=dict)),
                ('terms', models.TextField(blank=True)),
                ('extraction_metadata', models.JSONField(blank=True, default=dict)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='requests.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.utils.get_document_upload_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.TextField(blank=True)),
                ('items_data', models.JSONField(default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terms', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pos', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='requests.purchaserequest')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.utils.get_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('discrepancy', 'Discrepancy Found')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='requests.purchaserequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
